const ActionTypes = {
  LOAD_ALL_OFFERS: `LOAD_ALL_OFFERS`,
  CHANGE_CITY: `CHANGE_CITY`,
  NEED_AUTH: `NEED_AUTH`,
  SAVE_USER_DATA: `SAVE_USER_DATA`,
  LOAD_FAVORITES: `LOAD_FAVORITES`,
  CLEAR_FAVORITES: `CLEAR_FAVORITES`,
  ADD_TO_FAVORITES: `ADD_TO_FAVORITES`,
  REMOVE_FROM_FAVORITES: `REMOVE_FROM_FAVORITES`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
};

export default ActionTypes;
