const ActionTypes = {
  LOAD_ALL_OFFERS: `LOAD_ALL_OFFERS`,
  CHANGE_CITY: `CHANGE_CITY`,
  NEED_AUTH: `NEED_AUTH`,
  SAVE_USER_DATA: `SAVE_USER_DATA`,
  SWITCH_FAV_STATUS: `SWITCH_FAV_STATUS`,
};

export default ActionTypes;
